// Regenerate preview evidence from the article's current model; never change the model.
import {readFileSync,writeFileSync} from 'node:fs';
import {createHash} from 'node:crypto';
import {execFileSync} from 'node:child_process';
import {forward} from '../../src/toy_ref.mjs';
const modelURL=new URL('../../src/toy.json',import.meta.url);
const source=readFileSync(modelURL,'utf8'), model=JSON.parse(source);
const tokens=model.sentences.river,F=forward(model,tokens);
function row(i){
  return {index:i,position:i+1,token:tokens[i],e:F.E[i],q:F.Q[i],keys:F.K,values:F.V,
    rawScores:F.Sraw[i],scaledScores:F.Sraw[i].map(x=>x/Math.sqrt(model.d_k)),
    maskedScores:F.S[i].map(x=>Number.isFinite(x)?x:null),alpha:F.A[i],mixture:F.Mmsg[i],
    delta:F.Delta[i],updated:F.Enew[i],logits:F.logits[i],probabilities:F.probs[i],
    topVocabulary:model.vocab.map((token,j)=>({token,index:j,logit:F.logits[i][j],probability:F.probs[i][j]})).sort((a,b)=>b.probability-a.probability).slice(0,6)};
}
const shapes=Object.fromEntries(Object.entries({WQ:'W_Q',WK:'W_K',WV:'W_V',WO:'W_O',WVocab:'W_vocab'}).map(([k,v])=>[k,[model[v].length,model[v][0].length]]));
const pi=model.axes.short.e.indexOf('pos');
const positionIgnored=pi>=0&&['W_Q','W_K','W_V','W_vocab'].every(k=>model[k][pi].every(x=>x===0));
const data={schemaVersion:1,provenance:{source:'src/toy.json',reference:'src/toy_ref.mjs',
  repositoryCommit:execFileSync('git',['rev-parse','HEAD'],{cwd:new URL('../../',import.meta.url),encoding:'utf8'}).trim(),
  modelSha256:createHash('sha256').update(source).digest('hex'),snapshotDate:new Date().toISOString().slice(0,10),
  handDesigned:true,trained:false,positionIgnored,description:'Named-axis, single-head causal attention toy. Actual arithmetic from hand-designed weights, not a trained language model.',
  convention:'Row vectors. e=token embedding + position; q=e WQ; k=e WK; v=e WV; scores=q K^T/sqrt(dKey); mixture=alpha V; delta=mixture WO; updated=e+delta; logits=updated WVocab+b.',
  maskEncoding:'null means forbidden future score (negative infinity); its attention weight is zero.',
  predictionBoundary:'bank is receiver 7. Prediction after the full ten-token prefix uses receiver 10, the last the.'},
  tokens,vocabulary:model.vocab,dims:{T:tokens.length,dModel:model.d_model,dKey:model.d_k,dValue:model.d_v,vocabSize:model.vocab.length},
  shapes,axes:model.axes,bank:row(6),last:row(tokens.length-1)};
const freeze='\n(function freeze(v){if(v && typeof v === "object"){Object.values(v).forEach(freeze);Object.freeze(v);}})(globalThis.ATTENTION_PREVIEW_DATA);\n';
writeFileSync(new URL('toy-data.js',import.meta.url),'/* Generated by sync-data.mjs from src/toy.json; verify with check-data.mjs. */\nglobalThis.ATTENTION_PREVIEW_DATA = '+JSON.stringify(data,null,2)+';'+freeze);
console.log('Preview evidence synchronized:',data.dims,data.provenance.modelSha256);
