"""Execute the exact classroom snippets and cross-check the saved numerical model.

Run with a Python environment that already has PyTorch installed:
    python src/check_part1_torch.py
    python src/check_part1_torch.py --export-text
The latter prints the generated standalone lesson file; it does not run training.
"""
from contextlib import redirect_stdout
from html.parser import HTMLParser
from pathlib import Path
import ast
import io
import json
import sys

ROOT = Path(__file__).resolve().parent


class Snippets(HTMLParser):
    def __init__(self):
        super().__init__(convert_charrefs=True)
        self.items = []
        self.current = None
        self.text = []

    def handle_starttag(self, tag, attrs):
        if tag == "pre" and dict(attrs).get("data-torch"):
            self.current = dict(attrs)["data-torch"]
            self.text = []

    def handle_data(self, data):
        if self.current:
            self.text.append(data)

    def handle_endtag(self, tag):
        if tag == "pre" and self.current:
            self.items.append((self.current, "".join(self.text).strip()))
            self.current = None


parser = Snippets()
for file in sorted((ROOT / "sections1").glob("sec*.html")):
    parser.feed(file.read_text())
assert len(parser.items) >= 20, "Missing computational-stage snippets"
assert len({name for name, _ in parser.items}) == len(parser.items)
for name, source in parser.items:
    lines = source.splitlines()
    assert 2 <= len(lines) <= 5, (name, "expected 2–5 code lines")
    assert max(map(len, lines)) <= 85, (name, "line too long for the slide")
    ast.parse(source, filename=name)

header = '''# Part 1: executable PyTorch snippets in lecture order.
# Source: src/sections1/*.html. Generated by check_part1_torch.py --export-text.
# Run with Python and PyTorch installed. No datasets are downloaded.
# This constructs fresh teaching models and illustrates individual SGD updates.
# It does not reproduce the already-trained worksheet values or its named axes.
# The companion checker separately loads toy1.json to verify those values.
# The name model receives only one update, so its sampled text can be implausible.

'''
exported = header + "\n\n".join("# " + name + "\n" + source for name, source in parser.items) + "\n"
if "--export-text" in sys.argv:
    print(exported, end="")
    sys.exit(0)

import torch

torch.manual_seed(7)
scope = {"__name__": "__classroom_snippets__"}
before_step = None
for name, source in parser.items:
    if name == "training":
        before_step = [p.detach().clone() for p in scope["model"].parameters()]
    with redirect_stdout(io.StringIO()):
        exec(compile(source, name, "exec"), scope)
    if name == "windows":
        assert scope["X"].shape == (6, 3) and scope["y"].shape == (6,)
        assert scope["X"][3].tolist() == [1, 1, 2] and scope["y"][3].item() == 9
    if name == "embedding":
        assert scope["e"].shape == (1, 3, 2)
        assert scope["embedding"].padding_idx is None
    if name == "single-character-lookup":
        assert scope["char_id"].tolist() == [1] and scope["e_a"].shape == (1, 2)
        torch.testing.assert_close(scope["e_a"][0], scope["embedding"].weight[1])
    if name == "word-analogy":
        torch.testing.assert_close(scope["candidate"], scope["queen"])
        torch.testing.assert_close(scope["king"] - scope["man"], torch.tensor([0., 2.]))
    if name == "document-mean":
        assert scope["e_doc"].shape == (1, 2)
        reversed_rows = scope["doc_embedding"](scope["doc_ids"].flip(1)).mean(1)
        torch.testing.assert_close(scope["e_doc"], reversed_rows)
    if name == "image-encoder":
        assert scope["e_image"].shape == (1, 4)
    if name == "time-encoder":
        assert scope["e_time"].shape == (1, 3)
    if name == "flatten":
        assert scope["a0"].shape == (1, 6)
    if name == "hidden":
        assert scope["a1"].shape == (1, 32)
        assert torch.all(scope["a1"] >= 0)
    if name == "relu-rule":
        torch.testing.assert_close(scope["after_relu"], torch.tensor([0., 0., 3.]))
    if name == "output":
        assert scope["z"].shape == (1, 27)
    if name == "model":
        assert sum(p.numel() for p in scope["model"].parameters()) == 1169
    if name == "batch-shapes":
        assert scope["a0_batch"].shape == (4, 6)
        assert scope["a1_batch"].shape == (4, 32)
        assert scope["z_batch"].shape == (4, 27)
        assert scope["hidden"].weight.shape == (32, 6)
        assert scope["hidden"].bias.shape == (32,)
        assert scope["output"].weight.shape == (27, 32)
        assert scope["output"].bias.shape == (27,)
        for j in range(4):
            torch.testing.assert_close(
                scope["z_batch"][j:j+1], scope["model"](scope["X"][j:j+1]))
    if name == "stable-softmax":
        torch.testing.assert_close(scope["p"], scope["z"].softmax(-1))
    if name == "loss":
        expected = -scope["p"][0, scope["target"].item()].log()
        torch.testing.assert_close(scope["loss"], expected)
    if name == "training":
        params = list(scope["model"].parameters())
        assert all(p.grad is not None and torch.isfinite(p.grad).all() for p in params)
        assert any(not torch.equal(old, new) for old, new in zip(before_step, params))
    if name == "generation-loop":
        assert scope["ctx"].shape == (1, 3)
        assert len(scope["name"]) <= 18 and "-" not in scope["name"]
        assert not scope["sample_next"](scope["ctx"]).requires_grad
    if name == "generation-choices":
        assert scope["ctx"].tolist() == [[0, 19, 1]]
        assert scope["greedy_id"].shape == scope["sampled_id"].shape == (1, 1)
        assert scope["greedy_id"].item() == scope["p"].argmax().item()
        assert 0 <= scope["sampled_id"].item() < 27
        assert not scope["p"].requires_grad
    if name == "word-output":
        assert scope["word_z"].shape == (1, 6)
    if name == "longer-window":
        assert scope["wide_hidden"].weight.shape == (32, 10)
    print("PASS", name)

standalone = ROOT.parent / "examples" / "part1_pytorch.py"
assert standalone.read_text() == exported, "Regenerate the standalone file from the HTML snippets"

# Fixture check: nn.Linear stores the transpose of the lecture's row-vector W.
toy = json.loads((ROOT / "toy1.json").read_text())
assert toy["activation"] == "relu"
assert any(isinstance(layer, torch.nn.ReLU) for layer in scope["model"])
model = scope["model"].double()
embedding, hidden, output = scope["embedding"], scope["hidden"], scope["output"]
with torch.no_grad():
    embedding.weight.copy_(torch.tensor(toy["E"], dtype=torch.float64))
    hidden.weight.copy_(torch.tensor(toy["W1"], dtype=torch.float64).T)
    hidden.bias.copy_(torch.tensor(toy["b1"], dtype=torch.float64))
    output.weight.copy_(torch.tensor(toy["W2"], dtype=torch.float64).T)
    output.bias.copy_(torch.tensor(toy["b2"], dtype=torch.float64))
    worst = 0.0
    for row in toy["aabid_rows"]:
        got = model(torch.tensor([row["ids"]])).softmax(-1)[0]
        expected = torch.tensor(row["probabilities"], dtype=torch.float64)
        torch.testing.assert_close(got, expected, atol=1e-12, rtol=1e-12)
        worst = max(worst, (got - expected).abs().max().item())
print(f"PASS all {len(parser.items)} snippets; saved model's six rows match within {worst:.3g}")

# Independent reference for every probability used by the worked browser run.
# The draw itself uses the browser RNG, not torch.multinomial's different RNG.
with torch.no_grad():
    for context, chosen, expected in [
        ("---", "s", 0.19583967623795875),
        ("--s", "a", 0.32189935464079333),
        ("-sa", "m", 0.06398357772422884),
        ("sam", "-", 0.28973532963383036),
    ]:
        ids = torch.tensor([[toy["vocab"].index(c) for c in context]])
        probabilities = model(ids).softmax(-1)[0]
        assert abs(probabilities[toy["vocab"].index(chosen)].item() - expected) < 1e-12
    context, letters = [0, 0, 0], []
    for _ in range(18):
        next_id = model(torch.tensor([context])).argmax(-1).item()
        if next_id == 0:
            break
        letters.append(toy["vocab"][next_id])
        context = context[1:] + [next_id]
    assert "".join(letters) == "san" and next_id == 0
print("PASS worked sampling-run probabilities and complete greedy san run match PyTorch")

# This diagram concerns only aab -> i, not the six-row batch or the trainer's
# extra embedding penalties. Repeated lookups must accumulate into one row.
ctx = torch.tensor([[toy["vocab"].index(c) for c in "aab"]])
target = torch.tensor([toy["vocab"].index("i")])
looked_up = embedding(ctx)
logits = output(torch.relu(hidden(looked_up.flatten(1))))
one_loss = torch.nn.functional.cross_entropy(logits, target)
table_grad, lookup_grad = torch.autograd.grad(one_loss, (embedding.weight, looked_up))
a, b = toy["vocab"].index("a"), toy["vocab"].index("b")
nonzero_rows = torch.nonzero(table_grad.abs().sum(dim=1) > 0).flatten().tolist()
assert nonzero_rows == [a, b], nonzero_rows
torch.testing.assert_close(table_grad[a], lookup_grad[0, 0] + lookup_grad[0, 1])
torch.testing.assert_close(table_grad[b], lookup_grad[0, 2])
assert torch.count_nonzero(table_grad[target.item()]).item() == 0
updated = embedding.weight.detach() - 0.1 * table_grad
changed = torch.nonzero((updated != embedding.weight.detach()).any(dim=1)).flatten().tolist()
assert changed == [a, b], changed
print("PASS aab -> i: only embedding rows a/b get gradients; both a contributions add; plain SGD changes only those rows")

# Independently check the NumPy trainer's ReLU backward pass against autograd,
# including its existing embedding-axis penalties, for fresh and trained weights.
import numpy as np
import train_names as trainer

ids = np.asarray([row["ids"] for row in toy["aabid_rows"]])
targets = np.asarray([row["target_id"] for row in toy["aabid_rows"]])
for label, checkpoint in [("before", toy["before"]), ("trained", toy)]:
    params = {key: np.asarray(checkpoint[key]) for key in ["E", "W1", "b1", "W2", "b2"]}
    ce, penalty, gradients = trainer.loss_and_grads(params, ids, targets)
    tensors = {key: torch.tensor(value, dtype=torch.float64, requires_grad=True) for key, value in params.items()}
    a0 = tensors["E"][torch.tensor(ids)].flatten(1)
    a1 = torch.relu(a0 @ tensors["W1"] + tensors["b1"])
    logits = a1 @ tensors["W2"] + tensors["b2"]
    objective = torch.nn.functional.cross_entropy(logits, torch.tensor(targets))
    signs = torch.tensor([1. if c in trainer.VOWELS else -1. for c in trainer.VOCAB[1:]], dtype=torch.float64)
    violations = torch.relu(trainer.VOWEL_MARGIN - signs * tensors["E"][1:, 0])
    objective = objective + trainer.VOWEL_PENALTY * violations.square().mean() + 0.02 * tensors["E"][0, 0].square()
    objective.backward()
    np.testing.assert_allclose(objective.detach().item(), ce + penalty, atol=1e-12, rtol=1e-12)
    for key in params:
        np.testing.assert_allclose(tensors[key].grad.numpy(), gradients[key], atol=1e-12, rtol=1e-12)
    print(f"PASS {label} NumPy objective and all 1,169 parameter gradients agree with PyTorch")
