"""Execute the exact classroom snippets and cross-check the saved numerical model.

Run with a Python environment that already has PyTorch installed:
    python src/check_part1_torch.py
    python src/check_part1_torch.py --export-text
The latter prints the generated standalone lesson file; it does not run training.
"""
from contextlib import redirect_stdout
from html.parser import HTMLParser
from pathlib import Path
import ast
import io
import json
import sys

ROOT = Path(__file__).resolve().parent


class Snippets(HTMLParser):
    def __init__(self):
        super().__init__(convert_charrefs=True)
        self.items = []
        self.current = None
        self.text = []

    def handle_starttag(self, tag, attrs):
        if tag == "pre" and dict(attrs).get("data-torch"):
            self.current = dict(attrs)["data-torch"]
            self.text = []

    def handle_data(self, data):
        if self.current:
            self.text.append(data)

    def handle_endtag(self, tag):
        if tag == "pre" and self.current:
            self.items.append((self.current, "".join(self.text).strip()))
            self.current = None


parser = Snippets()
for file in sorted((ROOT / "sections1").glob("sec*.html")):
    parser.feed(file.read_text())
assert len(parser.items) >= 20, "Missing computational-stage snippets"
assert len({name for name, _ in parser.items}) == len(parser.items)
for name, source in parser.items:
    lines = source.splitlines()
    assert 2 <= len(lines) <= 5, (name, "expected 2–5 code lines")
    assert max(map(len, lines)) <= 85, (name, "line too long for the slide")
    ast.parse(source, filename=name)

header = '''# Part 1: executable PyTorch snippets in lecture order.
# Source: src/sections1/*.html. Generated by check_part1_torch.py --export-text.
# Run with Python and PyTorch installed. No datasets are downloaded.
# This constructs fresh teaching models and illustrates individual SGD updates.
# It does not reproduce the already-trained worksheet values or its named axes.
# The companion checker separately loads toy1.json to verify those values.
# The name model receives only one update, so its sampled text can be implausible.

'''
exported = header + "\n\n".join("# " + name + "\n" + source for name, source in parser.items) + "\n"
if "--export-text" in sys.argv:
    print(exported, end="")
    sys.exit(0)

import torch

torch.manual_seed(7)
scope = {"__name__": "__classroom_snippets__"}
before_step = None
for name, source in parser.items:
    if name == "training":
        before_step = [p.detach().clone() for p in scope["model"].parameters()]
    with redirect_stdout(io.StringIO()):
        exec(compile(source, name, "exec"), scope)
    if name == "windows":
        assert scope["X"].shape == (6, 3) and scope["y"].shape == (6,)
        assert scope["X"][3].tolist() == [1, 1, 2] and scope["y"][3].item() == 9
    if name == "embedding":
        assert scope["e"].shape == (1, 3, 2)
        assert scope["embedding"].padding_idx is None
    if name == "word-analogy":
        torch.testing.assert_close(scope["candidate"], scope["queen"])
        torch.testing.assert_close(scope["king"] - scope["man"], torch.tensor([0., 2.]))
    if name == "document-mean":
        assert scope["e_doc"].shape == (1, 2)
        reversed_rows = scope["doc_embedding"](scope["doc_ids"].flip(1)).mean(1)
        torch.testing.assert_close(scope["e_doc"], reversed_rows)
    if name == "image-encoder":
        assert scope["e_image"].shape == (1, 4)
    if name == "time-encoder":
        assert scope["e_time"].shape == (1, 3)
    if name == "flatten":
        assert scope["a0"].shape == (1, 6)
    if name == "hidden":
        assert scope["a1"].shape == (1, 32)
    if name == "output":
        assert scope["z"].shape == (1, 27)
    if name == "model":
        assert sum(p.numel() for p in scope["model"].parameters()) == 1169
    if name == "stable-softmax":
        torch.testing.assert_close(scope["p"], scope["z"].softmax(-1))
    if name == "loss":
        expected = -scope["p"][0, scope["target"].item()].log()
        torch.testing.assert_close(scope["loss"], expected)
    if name == "training":
        params = list(scope["model"].parameters())
        assert all(p.grad is not None and torch.isfinite(p.grad).all() for p in params)
        assert any(not torch.equal(old, new) for old, new in zip(before_step, params))
    if name == "generation-loop":
        assert scope["ctx"].shape == (1, 3)
        assert len(scope["name"]) <= 18 and "-" not in scope["name"]
        assert not scope["sample_next"](scope["ctx"]).requires_grad
    if name == "word-output":
        assert scope["word_z"].shape == (1, 6)
    if name == "longer-window":
        assert scope["wide_hidden"].weight.shape == (32, 10)
    print("PASS", name)

standalone = ROOT.parent / "examples" / "part1_pytorch.py"
assert standalone.read_text() == exported, "Regenerate the standalone file from the HTML snippets"

# Fixture check: nn.Linear stores the transpose of the lecture's row-vector W.
toy = json.loads((ROOT / "toy1.json").read_text())
model = scope["model"].double()
embedding, hidden, output = scope["embedding"], scope["hidden"], scope["output"]
with torch.no_grad():
    embedding.weight.copy_(torch.tensor(toy["E"], dtype=torch.float64))
    hidden.weight.copy_(torch.tensor(toy["W1"], dtype=torch.float64).T)
    hidden.bias.copy_(torch.tensor(toy["b1"], dtype=torch.float64))
    output.weight.copy_(torch.tensor(toy["W2"], dtype=torch.float64).T)
    output.bias.copy_(torch.tensor(toy["b2"], dtype=torch.float64))
    worst = 0.0
    for row in toy["aabid_rows"]:
        got = model(torch.tensor([row["ids"]])).softmax(-1)[0]
        expected = torch.tensor(row["probabilities"], dtype=torch.float64)
        torch.testing.assert_close(got, expected, atol=1e-12, rtol=1e-12)
        worst = max(worst, (got - expected).abs().max().item())
print(f"PASS all {len(parser.items)} snippets; saved model's six rows match within {worst:.3g}")
