"""Nine teaching prompts tied to the existing trained-model measurements."""
EXAMPLES = [
    dict(id='background', title='Background finds background', mode='similarity', block=12, head=1, query=182, source=70,
         look='Purple marks the lower-right background patch. Look for gold around the dog, with less gold on its body.',
         takeaway='Patch features can separate regions that look like foreground and background. This is a similarity pattern, not a predicted segmentation mask.'),
    dict(id='corners', title='Check a true corner', mode='similarity', block=12, head=1, query=1, source=183, precision=4,
         look='Now the reference is the top-left corner. Its strongest matches are the other three corners, with cosine similarity almost 1.',
         takeaway='A strong feature match need not identify an object part. Inspect where the matches occur before assigning them a meaning.'),
    dict(id='ears', title='One ear finds the other side', mode='similarity', block=12, head=1, query=74, source=82,
         look='Purple marks the left side of the dog’s head. P82, on the opposite side, is the strongest other match.',
         takeaway='Distant patches can have similar learned features. This correspondence appears in this trained model and photograph; it is not guaranteed for every image.'),
    dict(id='nose', title='Move the reference to the nose', mode='similarity', block=12, head=1, query=63, source=77,
         look='The query moves to P63 near the nose. The brightest matches move toward nearby face and muzzle patches.',
         takeaway='The map answers a question about the selected patch. Changing the reference changes which features are being compared.'),
    dict(id='fur', title='Follow the body’s dark fur', mode='similarity', block=12, head=1, query=147, source=162,
         look='The reference is now on the chest. Notice the group of similar patches lower on the dog, rather than around its nose.',
         takeaway='Different regions of one object can have different features. Similarity need not highlight the entire dog uniformly.'),
    dict(id='early', title='Rewind the ear example to block 1', mode='similarity', block=1, head=1, query=74, source=82,
         look='Keep the same P74-to-P82 ear pair as example 3. Its cosine similarity is now 0.322; after block 12 it was 0.902.',
         takeaway='The pixels stay fixed while the representation changes through the blocks. The late-block match was not already this strong at the start.'),
    dict(id='attention', title='Ask what the ear reads', mode='attention', block=4, head=1, query=74, source=60,
         look='Switch to attention: block 4, head 1, query P74. P60’s value row is multiplied by 9.09% in this head’s message.',
         takeaway='An attention weight scales a source’s value in the query’s message. Feature similarity compares patch representations.'),
    dict(id='heads', title='Change only the attention head', mode='attention', block=4, head=2, query=74, source=38,
         look='The image, query and block stay fixed. Head 2 puts its largest patch weight on P38, at about 2.29%.',
         takeaway='Heads learn different ways to gather information. Gold is rescaled within each attention map, so compare percentages, not brightness, across heads.'),
    dict(id='cls', title='Let CLS gather an image summary', mode='attention', block=12, head=1, query=0, source=64,
         look='The query is now CLS, not an image patch. In this head, P64 near the face receives about 24.86% of the weight.',
         takeaway='CLS can gather patch information for classification. This is one head in one block, not a complete explanation of the final label.'),
]
