"""Nine teaching prompts tied to the existing trained-model measurements."""
EXAMPLES = [
    dict(id='background', title='Background finds background', mode='similarity', block=12, head=1, query=182, source=70,
         look='The background query finds gold around the dog.',
         takeaway='Learned features can separate foreground and background.',
         detail='Purple marks the lower-right background patch. Gold appears around the dog, with less on its body. This is a similarity pattern, not a predicted segmentation mask.'),
    dict(id='corners', title='Check a true corner', mode='similarity', block=12, head=1, query=1, source=183, precision=4,
         look='The top-left corner matches the other three corners.',
         takeaway='A strong match need not be an object part.',
         detail='The strongest matches have cosine similarity almost 1. Inspect where the matches occur before assigning them a meaning.'),
    dict(id='ears', title='One ear finds the other side', mode='similarity', block=12, head=1, query=74, source=82,
         look='The ear query matches the other side of the head.',
         takeaway='Similar features can connect distant patches.',
         detail='Purple marks P74 on the left side of the dog’s head. P82 on the opposite side is the strongest other match. This correspondence is specific to this trained model and photograph; it is not guaranteed for every image.'),
    dict(id='nose', title='Move the reference to the nose', mode='similarity', block=12, head=1, query=63, source=77,
         look='The nose query finds nearby face and muzzle patches.',
         takeaway='Change the query; change the matches.',
         detail='The query moves to P63 near the nose. The map compares every patch representation with this selected reference.'),
    dict(id='fur', title='Follow the body’s dark fur', mode='similarity', block=12, head=1, query=147, source=162,
         look='The chest query finds similar fur lower on the dog.',
         takeaway='One object can contain several kinds of features.',
         detail='The reference is now on the chest. Similarity need not highlight the entire dog uniformly: the lower body and nose have different features.'),
    dict(id='early', title='Rewind to block 1', mode='similarity', block=1, head=1, query=74, source=82,
         look='Same ear pair: 0.322 here → 0.902 at block 12.',
         takeaway='Same pixels. Different features after each block.',
         detail='Keep the P74-to-P82 ear pair from example 3. Its cosine similarity is 0.322 after block 1 and 0.902 after block 12. The representation changes while the pixels stay fixed; not every pair’s similarity must increase.'),
    dict(id='attention', title='Ask what the ear reads', mode='attention', block=4, head=1, query=74, source=60,
         look='The ear query gives P60’s value 9.09% weight.',
         takeaway='Attention mixes values into the query’s message.',
         detail='This is block 4, head 1, query P74. An attention weight scales a source’s value; feature similarity instead compares the patch representations. These are different measurements.'),
    dict(id='heads', title='Change only the attention head', mode='attention', block=4, head=2, query=74, source=38,
         look='Same query and block. Head 2 favours P38.',
         takeaway='Different heads gather different information.',
         detail='Head 2 puts its largest patch weight on P38, at about 2.29%. Teal is rescaled within each attention map: compare percentages, not brightness, across heads.'),
    dict(id='cls', title='Let CLS gather an image summary', mode='attention', block=12, head=1, query=0, source=64,
         look='CLS gives the face patch P64 about 25% weight.',
         takeaway='CLS gathers image information for classification.',
         detail='CLS is the query: an extra token, not an image patch. P64 receives about 24.86% of the weight in block 12, head 1. This is one head in one block, not a complete explanation of the final label.'),
]
