import {SPECIAL,KINDS,LABELS,tokenize,detokenize,makeContext,randomGenerator,chooseToken} from './core.mjs';
const $=id=>document.getElementById(id),CDN='https://cdn.jsdelivr.net/npm/onnxruntime-web@1.30.0/dist/';
let metadata,vocab,examples,stoi,state=null,busy=false,stopped=false;
const descriptions={mlp:'64 embeddings, concatenated',attention:'1 head × 64 coordinates',multihead:'4 heads × 16 coordinates'};
for(const kind of KINDS){const article=document.createElement('article');article.innerHTML=`<h3>${LABELS[kind]}</h3><p class="model-description">${descriptions[kind]}</p><p id="${kind}-output" class="generated-text empty">Choose a prompt, then generate.</p><p id="${kind}-timing" class="timing">Not run yet</p>`;$('outputs').append(article);}
async function json(path){const response=await fetch(path);if(!response.ok)throw new Error(`Could not load ${path}. Reload to try again.`);return response.json();}
function updateTokens(){if(!stoi)return;const tokens=tokenize($('prompt').value),unknown=[...new Set(tokens.filter(t=>!stoi.has(t)))];$('token-note').textContent=`${tokens.length} prompt tokens. The model sees the last ${Math.min(64,tokens.length+1)} IDs, including BOS if it still fits.${unknown.length?' Unknown words become UNK: '+unknown.slice(0,15).join(', ')+(unknown.length>15?'…':'')+'.':''}`;$('token-note').classList.toggle('error',unknown.length>0);}
function selectExample(){const e=examples.prompts.find(e=>e.id===$('example').value);if(!e)return;$('prompt').value=e.prompt;$('example-note').textContent=e.note;$('source-details').hidden=!e.source_text;$('source-details').open=false;$('source-text').textContent=e.source_text||'';$('source-credit').textContent=e.source_text?`TinyStories source row ${e.row_idx}. ${e.split} split in our experiment. ${e.token_count} tokens in the complete story.`:'';updateTokens();}
function lock(value){busy=value;for(const id of ['generate','example','prompt','decoding','token-count','backend'])$(id).disabled=value;$('temperature').disabled=value||$('decoding').value==='greedy';$('seed').disabled=value||$('decoding').value==='greedy';$('stop').hidden=!value;$('stop').disabled=false;}
async function release(sessions){for(const session of Object.values(sessions||{}))await session.release();}
async function createSessions(provider){const sessions={};try{for(const kind of KINDS){$('runtime-status').textContent=`Loading ${LABELS[kind]} (${provider})…`;sessions[kind]=await ort.InferenceSession.create(metadata.models[kind].file,{executionProviders:[provider],graphOptimizationLevel:'all'});const input=new ort.Tensor('int32',makeContext([SPECIAL.bos]),[1,64]);const result=await sessions[kind].run({input_ids:input});chooseToken(result.logits.data,'greedy');input.dispose();result.logits.dispose();}return sessions;}catch(error){await release(sessions);throw error;}}
async function loadModels(){const requested=$('backend').value;if(state?.requested===requested)return state;if(state){await release(state.sessions);state=null;}if(!globalThis.ort)throw new Error('ONNX Runtime did not load. Check your connection and reload.');ort.env.wasm.wasmPaths=CDN;ort.env.wasm.numThreads=1;
  let sessions,backend,fallback='';const start=performance.now();
  if(requested!=='wasm'&&navigator.gpu){try{sessions=await createSessions('webgpu');backend='WebGPU';}catch(error){if(requested==='webgpu')throw error;fallback='WebGPU could not run these models. ';}}
  if(!sessions){if(requested==='webgpu')throw new Error('WebGPU is unavailable. Select WASM or the automatic runtime.');sessions=await createSessions('wasm');backend='WASM';}
  state={sessions,backend,requested};$('runtime-status').textContent=`${backend} ready`;$('load-note').textContent=`${fallback}Load and warm-up: ${((performance.now()-start)/1000).toFixed(2)} s. Excluded from generation timings.`;return state;
}
async function generate(kind,session,ids,settings){const history=[SPECIAL.bos,...ids],generated=[],random=randomGenerator(settings.seed),started=performance.now();let inferenceMs=0,calls=0,reason='Token limit';
  const output=$(`${kind}-output`);output.classList.remove('empty');output.replaceChildren();const prefix=document.createElement('span');prefix.className='prompt-text';prefix.textContent=$('prompt').value.trim();const continuation=document.createElement('span');output.append(prefix,continuation);
  for(let step=0;step<settings.limit;step++){if(stopped){reason='Stopped';break;}const input=new ort.Tensor('int32',makeContext(history),[1,64]);const tick=performance.now();let result;try{result=await session.run({input_ids:input});inferenceMs+=performance.now()-tick;calls++;const next=chooseToken(result.logits.data,settings.mode,settings.temperature,random);if(next===SPECIAL.eos){reason='EOS';break;}generated.push(next);history.push(next);}finally{input.dispose();result?.logits.dispose();}
    const text=detokenize(generated.map(id=>vocab.itos[id]));
    continuation.textContent=(prefix.textContent&&!/^[.,!?;:%)\]}]/u.test(text)?' ':'')+text;await new Promise(r=>setTimeout(r,0));
  }
  const elapsed=performance.now()-started;
  $(`${kind}-timing`).textContent=`${generated.length} new tokens · ${reason} · ${(elapsed/1000).toFixed(2)} s total · ${calls?(inferenceMs/calls).toFixed(1):'0'} ms/model call · ${state.backend}`;
  return {ids:generated,calls,reason,inference_ms:inferenceMs,total_ms:elapsed,backend:state.backend};
}
$('generation-form').addEventListener('submit',async event=>{event.preventDefault();if(busy||!metadata)return;lock(true);stopped=false;$('load-note').classList.remove('error');for(const kind of KINDS){$(`${kind}-output`).textContent='Waiting…';$(`${kind}-timing`).textContent='';}
  try{const runtime=await loadModels();const ids=tokenize($('prompt').value).map(t=>stoi.get(t)??SPECIAL.unk);const settings={mode:$('decoding').value,limit:Number($('token-count').value),temperature:Number($('temperature').value),seed:Number($('seed').value)};const results={};for(const kind of KINDS){if(stopped){$(`${kind}-output`).textContent='Not run (stopped).';continue;}results[kind]=await generate(kind,runtime.sessions[kind],ids,settings);}globalThis.lastComparison={settings,results};}
  catch(error){$('load-note').textContent=error.message||'Generation failed. Try WASM or reload.';$('load-note').classList.add('error');$('runtime-status').textContent='Could not finish';for(const kind of KINDS)if($(`${kind}-output`).textContent==='Waiting…')$(`${kind}-output`).textContent='Not run.';}
  finally{lock(false);}
});
$('stop').addEventListener('click',()=>{stopped=true;$('stop').disabled=true;});
$('example').addEventListener('change',selectExample);
$('prompt').addEventListener('input',()=>{$('example').value='custom';$('example-note').textContent='Custom prompt. These small models were trained on children’s stories, not instructions or factual answers.';$('source-details').hidden=true;updateTokens();});
$('decoding').addEventListener('change',()=>lock(false));
async function init(){try{[metadata,vocab,examples]=await Promise.all([json('./models/metadata.json'),json('./models/vocab.json'),json('./examples.json')]);stoi=new Map(vocab.itos.map((t,i)=>[t,i]));$('example').replaceChildren();for(const e of examples.prompts){const option=document.createElement('option');option.value=e.id;option.textContent=e.label;$('example').append(option);}const custom=document.createElement('option');custom.value='custom';custom.textContent='Your own prompt';$('example').append(custom);$('example').disabled=false;selectExample();const comparison=await json('./models/comparison.json');for(const kind of KINDS){const a=comparison.aggregate[kind],r=comparison.runs[kind][0],row=document.createElement('tr');const cells=[LABELS[kind],r.parameter_count.toLocaleString(),`${a.test_loss.mean.toFixed(3)} ± ${a.test_loss.sample_std.toFixed(3)}`,`${a.test_perplexity.mean.toFixed(2)} ± ${a.test_perplexity.sample_std.toFixed(2)}`,`${a.runtime_seconds.mean.toFixed(1)} ± ${a.runtime_seconds.sample_std.toFixed(1)} s`];for(const text of cells){const cell=document.createElement('td');cell.textContent=text;row.append(cell);}$('result-rows').append(row);}
  for(const [index,kind] of KINDS.entries())document.querySelectorAll('.model-description')[index].textContent=`${descriptions[kind]} · ${(metadata.models[kind].bytes/1e6).toFixed(2)} MB FP32`;
  $('protocol-note').textContent=`Mean ± sample SD over seeds 11, 29 and 47. ${comparison.protocol.steps.toLocaleString()} updates per run, batch size 512, up to ${(comparison.protocol.steps*512).toLocaleString()} supervised targets. Best validation checkpoint, then all 120,393 test targets. Training time includes validation checks, excludes data preparation and final test scoring. Measured on Apple M2 Max (${comparison.environment.accelerator}), ${comparison.created_utc.slice(0,10)}. Browser models use seed 11.`;
  $('load-note').textContent=`First run downloads ${(Object.values(metadata.models).reduce((s,m)=>s+m.bytes,0)/1e6).toFixed(1)} MB of model weights plus the runtime.`;$('generate').disabled=false;
 }catch(error){$('load-note').textContent=error.message;$('load-note').classList.add('error');}}
init();
